### ISSUE TITLE
Setting default options?

### ISSUE THREAD

**Issue by webplusdata** [simov/screenshot-capture#13]
Hi. Thanks for the great extension. Is it possible to set some default options upon install? I was thinking something like this, but find the code in the extension is over my head:

```
var initialState = {
  method: 'crop',
  format: 'png',
  save: 'url',
  dpr: true,
  icon: false
};
```

Is something like this possible? Thanks :)

**Comment by simov** [comment]
The default options are the ones you see when you open up the options page for the first time. Otherwise you can clone the extension and set those yourself. Put a breakpoint after this line https://github.com/simov/screenshot-capture/blob/main/background/index.js#L4 to see what is the configuration data structure.

**Comment by webplusdata** [comment]
Thanks simov :)
